### ISSUE TITLE
Language filter key combo is default 'lock' screen combo in Ubuntu

### ISSUE THREAD

**Issue by charlesmilam** [Coteh/syntaxdb-atom-plugin#14]
Key combination Ctrl+Alt+L for the 'Language Filter' is also the default key combination for locking the screen in Ubuntu (perhaps other Linux distros).

Work around is to select 'Language Filter' from the 'Packages' menu in Atom.

A nice feature would be to allow the user to assign custom key combinations.

**Comment by Coteh** [comment]
Hey Charles! Yes I am aware of this issue. I was trying out the plugin on a Ubuntu-based machine not too long ago and noticed that Ctrl+Alt+L was mapped to screen lock. I had written down about this issue but I guess I forgot to write it down as an issue on here. 😝  
Thanks for letting me know! I'll add all these to the roadmap and keep this issue open.

**Comment by Coteh** [comment]
It's been a very long time since this issue was initially raised, but I wanted to finally address it.

Seems like as of Ubuntu 18.04, the lock screen shortcut is now Super + L rather than Ctrl + Alt + L. However, it appears to still be Ctrl + Alt + L on KDE (which is installed on distros such as Linux Mint). I will be changing the default bind in #56, but I will not add a feature to assign custom key combinations because Atom already has a feature to override the default keybinds in Preferences -> Keybindings.
